name: CI

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.80.0"

      - name: Build website
        run: hugo --minify -s "src"
      - uses: shallwefootball/s3-upload-action@master
        name: deploy to s3
        with:
          aws_key_id: ${{ secrets.IAM_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.IAM_SECRET_ACCESS_KEY}}
          aws_bucket: ${{ secrets.AWS_BUCKET }}
          source_dir: "./src/public"
          destination_dir: ""

      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: #logs
          SLACK_COLOR: ${{ job.status }}
          SLACK_TITLE: erik.hedberg.at deployment
          MSG_MINIMAL: commit
